### ISSUE TITLE
The test dataset is empty.

### ISSUE THREAD

**Issue by chenzixuan99** [mlzxy/imop#1]
Hi there,

Thank you for sharing such a wonderful project!

Following the instructions in the README file, I downloaded the dataset from "https://rutgers.app.box.com/s/icwvszhcb5jvp8zr33htpqboebk2aupq". However, when I tried to run the evaluation code, I found that there are no images in any of the task folders within the "base_tests" and "novel_tests" directories, which prevents the evaluation process from running.

Is it possible that some files were missed when uploading the dataset? Or are there additional steps I need to follow to successfully run the evaluation?

Looking forward to your reply!

**Comment by BrightMoonStar** [comment]
> 你好呀，
> 
> 感谢您分享如此精彩的项目！
> 
> 按照 README 文件中的说明，我从“ https://rutgers.app.box.com/s/icwvszhcb5jvp8zr33htpqboebk2aupq ”下载了数据集。然而，当我尝试运行评估代码时，我发现“base_tests”和“novel_tests”目录下的任何任务文件夹中都没有图像，这阻止了评估过程的运行。
> 
> 上传数据集时是否有可能遗漏了一些文件？或者我需要遵循其他步骤才能成功运行评估？
> 
> 期待你的答复！

The same question

**Comment by mlzxy** [comment]
Hi, 

Thanks for pointing this out. Please install this RLBench fork https://github.com/mlzxy/RLBench. This branch does not read test images during evaluation (as they are not used anyway), provide color information (e.g., when stacking blocks, it makes sure the one-shot demonstration and testing scene has the same target block color), and fixes a small bug of the success criterion of the place cup task.


I have updated the README.
